### ISSUE TITLE
Add intructions on how to use library.

### ISSUE THREAD

**Issue by FuryingFox** [Sann0/PyMeow#1]
Could be good for newbies 👍

**Comment by Sann0** [comment]
I could write some basics up to get started. But IMO the function names and the examples show how to use it. Of course, it is assumed that you are familiar or atleast know the basics of game hacking / memory editing itself.

**Comment by FuryingFox** [comment]
I know bruda, but you shall add a installation because .pyw files are confusing

**Comment by Sann0** [comment]
Installation instructions added in https://github.com/Sann0/PyMeow/commit/b40718b84476ea6e933e749b1c6375836685ccf6
